"""add_inventory_items

Revision ID: 458992f6ed13
Revises:
Create Date: 2026-02-27 15:08:30.505525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "458992f6ed13"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("value", sa.String(length=200), nullable=True),
        sa.Column("repurchase", sa.Boolean(), nullable=True),
        sa.Column("expired_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_inventory_items_brand", "inventory_items", ["brand"], unique=False
    )
    op.create_index(
        "ix_inventory_items_category", "inventory_items", ["category"], unique=False
    )
    op.create_index(
        "ix_inventory_items_expired_date",
        "inventory_items",
        ["expired_date"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_items_repurchase", "inventory_items", ["repurchase"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inventory_items_repurchase", table_name="inventory_items")
    op.drop_index("ix_inventory_items_expired_date", table_name="inventory_items")
    op.drop_index("ix_inventory_items_category", table_name="inventory_items")
    op.drop_index("ix_inventory_items_brand", table_name="inventory_items")
    op.drop_table("inventory_items")
    # ### end Alembic commands ###
